<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "laws_online".
 *
 * @property integer $id
 * @property string $gh_user_name
 * @property integer $gh_user_id
 * @property string $gh_user_mobile
 * @property string $content
 * @property string $relpy
 * @property integer $lawyer_id
 * @property integer $create_time
 * @property integer $reply_time
 */
class LawsOnline extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'laws_online';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gh_user_id', 'content'], 'required'],
            [['gh_user_id', 'lawyer_id', 'create_time', 'reply_time'], 'integer'],
            [['content', 'relpy'], 'string'],
            [['gh_user_name', 'gh_user_mobile'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'gh_user_name' => '会员昵称',
            'gh_user_id' => '爱工惠会员ID',
            'gh_user_mobile' => '会员手机号',
            'content' => '内容',
            'relpy' => '回复内容',
            'lawyer_id' => '律师',
            'create_time' => '发布时间',
            'reply_time' => '回复时间',
        ];
    }

    public function beforeSave($insert)
    {
        if(!$this->isNewRecord){
            $this->reply_time=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
