<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "laws_qa".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $create_time
 * @property string $from
 * @property integer $read_count
 */
class LawsQa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'laws_qa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'content','from'], 'required'],
            [['content'], 'string'],
            [['create_time', 'read_count'], 'integer'],
            [['title', 'from'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'content' => '内容',
            'create_time' => '发布时间',
            'from' => '来源',
            'read_count' => '阅读数',
        ];
    }
    public function beforeSave($insert)
    {
        $this->create_time=time();
        $this->read_count=0;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
